
package generatedSources.DataMgt.schemas.dynamics.microsoft.codeunit.webdatamgt;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-18T00:50:38.619+02:00
 * Generated source version: 3.5.0
 *
 */
public final class WebDataMgtPort_WebDataMgtPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", "WebDataMgt");

    private WebDataMgtPort_WebDataMgtPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebDataMgt.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WebDataMgt ss = new WebDataMgt(wsdlURL, SERVICE_NAME);
        WebDataMgtPort port = ss.getWebDataMgtPort();

        {
        System.out.println("Invoking makesByType...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.ins_makes.Root _makesByType_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.ins_makes.Root> _makesByType_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.ins_makes.Root>(_makesByType_iTableVal);
        int _makesByType_makeType = 0;
        port.makesByType(_makesByType_iTable, _makesByType_makeType);

        System.out.println("makesByType._makesByType_iTable=" + _makesByType_iTable.value);

        }
        {
        System.out.println("Invoking charges...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root _charges_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> _charges_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root>(_charges_iTableVal);
        java.lang.String _charges_insCategoryCode = "";
        java.lang.String _charges_insCompanyCode = "";
        port.charges(_charges_iTable, _charges_insCategoryCode, _charges_insCompanyCode);

        System.out.println("charges._charges_iTable=" + _charges_iTable.value);

        }
        {
        System.out.println("Invoking banks...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _banks_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _banks_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_banks_iTableVal);
        port.banks(_banks_iTable);

        System.out.println("banks._banks_iTable=" + _banks_iTable.value);

        }
        {
        System.out.println("Invoking insSubCategories...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _insSubCategories_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _insSubCategories_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_insSubCategories_iTableVal);
        java.lang.String _insSubCategories_insCategoryCode = "";
        port.insSubCategories(_insSubCategories_iTable, _insSubCategories_insCategoryCode);

        System.out.println("insSubCategories._insSubCategories_iTable=" + _insSubCategories_iTable.value);

        }
        {
        System.out.println("Invoking endorsementReasons...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _endorsementReasons_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _endorsementReasons_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_endorsementReasons_iTableVal);
        port.endorsementReasons(_endorsementReasons_iTable);

        System.out.println("endorsementReasons._endorsementReasons_iTable=" + _endorsementReasons_iTable.value);

        }
        {
        System.out.println("Invoking coverCategories...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _coverCategories_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _coverCategories_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_coverCategories_iTableVal);
        java.lang.String _coverCategories_insCategoryCode = "";
        port.coverCategories(_coverCategories_iTable, _coverCategories_insCategoryCode);

        System.out.println("coverCategories._coverCategories_iTable=" + _coverCategories_iTable.value);

        }
        {
        System.out.println("Invoking taxOffices...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _taxOffices_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _taxOffices_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_taxOffices_iTableVal);
        port.taxOffices(_taxOffices_iTable);

        System.out.println("taxOffices._taxOffices_iTable=" + _taxOffices_iTable.value);

        }
        {
        System.out.println("Invoking packages...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _packages_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _packages_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_packages_iTableVal);
        java.lang.String _packages_insCategoryCode = "";
        java.lang.String _packages_insCompanyCode = "";
        java.lang.String _packages_insObjectTypeCode = "";
        port.packages(_packages_iTable, _packages_insCategoryCode, _packages_insCompanyCode, _packages_insObjectTypeCode);

        System.out.println("packages._packages_iTable=" + _packages_iTable.value);

        }
        {
        System.out.println("Invoking covers...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root _covers_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> _covers_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root>(_covers_iTableVal);
        java.lang.String _covers_insCategoryCode = "";
        java.lang.String _covers_insCompanyCode = "";
        port.covers(_covers_iTable, _covers_insCategoryCode, _covers_insCompanyCode);

        System.out.println("covers._covers_iTable=" + _covers_iTable.value);

        }
        {
        System.out.println("Invoking discounts...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root _discounts_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> _discounts_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root>(_discounts_iTableVal);
        java.lang.String _discounts_insCategoryCode = "";
        java.lang.String _discounts_insCompanyCode = "";
        port.discounts(_discounts_iTable, _discounts_insCategoryCode, _discounts_insCompanyCode);

        System.out.println("discounts._discounts_iTable=" + _discounts_iTable.value);

        }
        {
        System.out.println("Invoking insCompanies...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _insCompanies_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _insCompanies_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_insCompanies_iTableVal);
        port.insCompanies(_insCompanies_iTable);

        System.out.println("insCompanies._insCompanies_iTable=" + _insCompanies_iTable.value);

        }
        {
        System.out.println("Invoking customFieldsTemplates...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _customFieldsTemplates_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _customFieldsTemplates_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_customFieldsTemplates_iTableVal);
        port.customFieldsTemplates(_customFieldsTemplates_iTable);

        System.out.println("customFieldsTemplates._customFieldsTemplates_iTable=" + _customFieldsTemplates_iTable.value);

        }
        {
        System.out.println("Invoking coversByPackage...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root _coversByPackage_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> _coversByPackage_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root>(_coversByPackage_iTableVal);
        java.lang.String _coversByPackage_packageCode = "";
        java.lang.String _coversByPackage_insObjectTypeCode = "";
        java.lang.String _coversByPackage_insObjectTypeGroupCode = "";
        java.lang.String _coversByPackage_brokerNo = "";
        java.lang.String _coversByPackage_referenceDate = "";
        port.coversByPackage(_coversByPackage_iTable, _coversByPackage_packageCode, _coversByPackage_insObjectTypeCode, _coversByPackage_insObjectTypeGroupCode, _coversByPackage_brokerNo, _coversByPackage_referenceDate);

        System.out.println("coversByPackage._coversByPackage_iTable=" + _coversByPackage_iTable.value);

        }
        {
        System.out.println("Invoking makes...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _makes_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _makes_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_makes_iTableVal);
        port.makes(_makes_iTable);

        System.out.println("makes._makes_iTable=" + _makes_iTable.value);

        }
        {
        System.out.println("Invoking vesselClassSociety...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _vesselClassSociety_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _vesselClassSociety_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_vesselClassSociety_iTableVal);
        port.vesselClassSociety(_vesselClassSociety_iTable);

        System.out.println("vesselClassSociety._vesselClassSociety_iTable=" + _vesselClassSociety_iTable.value);

        }
        {
        System.out.println("Invoking durationTypes...");
        java.lang.String _durationTypes_insCategory = "";
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _durationTypes_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _durationTypes_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_durationTypes_iTableVal);
        port.durationTypes(_durationTypes_insCategory, _durationTypes_iTable);

        System.out.println("durationTypes._durationTypes_iTable=" + _durationTypes_iTable.value);

        }
        {
        System.out.println("Invoking insCategories...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _insCategories_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _insCategories_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_insCategories_iTableVal);
        port.insCategories(_insCategories_iTable);

        System.out.println("insCategories._insCategories_iTable=" + _insCategories_iTable.value);

        }
        {
        System.out.println("Invoking countriesRegions...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _countriesRegions_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _countriesRegions_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_countriesRegions_iTableVal);
        port.countriesRegions(_countriesRegions_iTable);

        System.out.println("countriesRegions._countriesRegions_iTable=" + _countriesRegions_iTable.value);

        }
        {
        System.out.println("Invoking insObjectTypes...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _insObjectTypes_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _insObjectTypes_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_insObjectTypes_iTableVal);
        java.lang.String _insObjectTypes_insCategoryCode = "";
        port.insObjectTypes(_insObjectTypes_iTable, _insObjectTypes_insCategoryCode);

        System.out.println("insObjectTypes._insObjectTypes_iTable=" + _insObjectTypes_iTable.value);

        }
        {
        System.out.println("Invoking chargesByPackage...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root _chargesByPackage_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> _chargesByPackage_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root>(_chargesByPackage_iTableVal);
        java.lang.String _chargesByPackage_packageCode = "";
        java.lang.String _chargesByPackage_insCategoryCode = "";
        java.lang.String _chargesByPackage_insCompanyCode = "";
        port.chargesByPackage(_chargesByPackage_iTable, _chargesByPackage_packageCode, _chargesByPackage_insCategoryCode, _chargesByPackage_insCompanyCode);

        System.out.println("chargesByPackage._chargesByPackage_iTable=" + _chargesByPackage_iTable.value);

        }
        {
        System.out.println("Invoking models...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _models_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _models_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_models_iTableVal);
        java.lang.String _models_makeCode = "";
        port.models(_models_iTable, _models_makeCode);

        System.out.println("models._models_iTable=" + _models_iTable.value);

        }
        {
        System.out.println("Invoking vehicleTypes...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _vehicleTypes_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _vehicleTypes_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_vehicleTypes_iTableVal);
        port.vehicleTypes(_vehicleTypes_iTable);

        System.out.println("vehicleTypes._vehicleTypes_iTable=" + _vehicleTypes_iTable.value);

        }
        {
        System.out.println("Invoking professions...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _professions_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _professions_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_professions_iTableVal);
        port.professions(_professions_iTable);

        System.out.println("professions._professions_iTable=" + _professions_iTable.value);

        }
        {
        System.out.println("Invoking customFields...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root _customFields_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> _customFields_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root>(_customFields_iTableVal);
        port.customFields(_customFields_iTable);

        System.out.println("customFields._customFields_iTable=" + _customFields_iTable.value);

        }
        {
        System.out.println("Invoking customerDiscountGroups...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _customerDiscountGroups_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _customerDiscountGroups_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_customerDiscountGroups_iTableVal);
        port.customerDiscountGroups(_customerDiscountGroups_iTable);

        System.out.println("customerDiscountGroups._customerDiscountGroups_iTable=" + _customerDiscountGroups_iTable.value);

        }
        {
        System.out.println("Invoking colors...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _colors_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _colors_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_colors_iTableVal);
        port.colors(_colors_iTable);

        System.out.println("colors._colors_iTable=" + _colors_iTable.value);

        }
        {
        System.out.println("Invoking customFieldsValues...");
        java.lang.String _customFieldsValues_code = "";
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _customFieldsValues_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _customFieldsValues_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_customFieldsValues_iTableVal);
        port.customFieldsValues(_customFieldsValues_code, _customFieldsValues_iTable);

        System.out.println("customFieldsValues._customFieldsValues_iTable=" + _customFieldsValues_iTable.value);

        }
        {
        System.out.println("Invoking customFieldsPerTemplate...");
        java.lang.String _customFieldsPerTemplate_templateCode = "";
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _customFieldsPerTemplate_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _customFieldsPerTemplate_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_customFieldsPerTemplate_iTableVal);
        port.customFieldsPerTemplate(_customFieldsPerTemplate_templateCode, _customFieldsPerTemplate_iTable);

        System.out.println("customFieldsPerTemplate._customFieldsPerTemplate_iTable=" + _customFieldsPerTemplate_iTable.value);

        }
        {
        System.out.println("Invoking brokers...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _brokers_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _brokers_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_brokers_iTableVal);
        port.brokers(_brokers_iTable);

        System.out.println("brokers._brokers_iTable=" + _brokers_iTable.value);

        }
        {
        System.out.println("Invoking vesselTypes...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _vesselTypes_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _vesselTypes_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_vesselTypes_iTableVal);
        port.vesselTypes(_vesselTypes_iTable);

        System.out.println("vesselTypes._vesselTypes_iTable=" + _vesselTypes_iTable.value);

        }
        {
        System.out.println("Invoking ports...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _ports_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _ports_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_ports_iTableVal);
        port.ports(_ports_iTable);

        System.out.println("ports._ports_iTable=" + _ports_iTable.value);

        }
        {
        System.out.println("Invoking attachedDocumentTypes...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _attachedDocumentTypes_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _attachedDocumentTypes_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_attachedDocumentTypes_iTableVal);
        port.attachedDocumentTypes(_attachedDocumentTypes_iTable);

        System.out.println("attachedDocumentTypes._attachedDocumentTypes_iTable=" + _attachedDocumentTypes_iTable.value);

        }
        {
        System.out.println("Invoking discountsByPackage...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root _discountsByPackage_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> _discountsByPackage_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root>(_discountsByPackage_iTableVal);
        java.lang.String _discountsByPackage_packageCode = "";
        java.lang.String _discountsByPackage_insCategoryCode = "";
        java.lang.String _discountsByPackage_insCompanyCode = "";
        port.discountsByPackage(_discountsByPackage_iTable, _discountsByPackage_packageCode, _discountsByPackage_insCategoryCode, _discountsByPackage_insCompanyCode);

        System.out.println("discountsByPackage._discountsByPackage_iTable=" + _discountsByPackage_iTable.value);

        }
        {
        System.out.println("Invoking relationTypes...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _relationTypes_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _relationTypes_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_relationTypes_iTableVal);
        port.relationTypes(_relationTypes_iTable);

        System.out.println("relationTypes._relationTypes_iTable=" + _relationTypes_iTable.value);

        }
        {
        System.out.println("Invoking counties...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _counties_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _counties_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_counties_iTableVal);
        port.counties(_counties_iTable);

        System.out.println("counties._counties_iTable=" + _counties_iTable.value);

        }
        {
        System.out.println("Invoking insObjectTypeGroups...");
        generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root _insObjectTypeGroups_iTableVal = null;
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> _insObjectTypeGroups_iTable = new javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root>(_insObjectTypeGroups_iTableVal);
        java.lang.String _insObjectTypeGroups_insCategoryCode = "";
        java.lang.String _insObjectTypeGroups_insSubCategoryCode = "";
        port.insObjectTypeGroups(_insObjectTypeGroups_iTable, _insObjectTypeGroups_insCategoryCode, _insObjectTypeGroups_insSubCategoryCode);

        System.out.println("insObjectTypeGroups._insObjectTypeGroups_iTable=" + _insObjectTypeGroups_iTable.value);

        }

        System.exit(0);
    }

}
