package generatedSources.DataMgt.schemas.dynamics.microsoft.codeunit.webdatamgt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-18T00:50:38.786+02:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "WebDataMgt",
                  wsdlLocation = "file:/D:/Ioannis/Documents/Projects/Code/Java/insuranceService/WSDLS/Statements/WebDataMgt/WebDataMgt.wsdl",
                  targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
public class WebDataMgt extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", "WebDataMgt");
    public final static QName WebDataMgtPort = new QName("urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", "WebDataMgt_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Ioannis/Documents/Projects/Code/Java/insuranceService/WSDLS/Statements/WebDataMgt/WebDataMgt.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebDataMgt.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Ioannis/Documents/Projects/Code/Java/insuranceService/WSDLS/Statements/WebDataMgt/WebDataMgt.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebDataMgt(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebDataMgt(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebDataMgt() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WebDataMgt(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebDataMgt(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebDataMgt(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WebDataMgtPort
     */
    @WebEndpoint(name = "WebDataMgt_Port")
    public WebDataMgtPort getWebDataMgtPort() {
        return super.getPort(WebDataMgtPort, WebDataMgtPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebDataMgtPort
     */
    @WebEndpoint(name = "WebDataMgt_Port")
    public WebDataMgtPort getWebDataMgtPort(WebServiceFeature... features) {
        return super.getPort(WebDataMgtPort, WebDataMgtPort.class, features);
    }

}
