
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package generatedSources.DataMgt.schemas.dynamics.microsoft.codeunit.webdatamgt;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-18T00:50:38.703+02:00
 * Generated source version: 3.5.0
 *
 */

@javax.jws.WebService(
                      serviceName = "WebDataMgt",
                      portName = "WebDataMgt_Port",
                      targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt",
                      wsdlLocation = "file:/D:/Ioannis/Documents/Projects/Code/Java/insuranceService/WSDLS/Statements/WebDataMgt/WebDataMgt.wsdl",
                      endpointInterface = "schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort")

public class WebDataMgt_PortImpl implements WebDataMgtPort {

    private static final Logger LOG = Logger.getLogger(WebDataMgt_PortImpl.class.getName());

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#makesByType(nav.dynamics.microsoft.xmlports.ins_makes.Root iTable, int makeType)*
     */
    public void makesByType(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.ins_makes.Root> iTable, int makeType) {
        LOG.info("Executing operation makesByType");
        System.out.println(iTable.value);
        System.out.println(makeType);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#charges(nav.dynamics.microsoft.xmlports.discount_charges.Root iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode)*
     */
    public void charges(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode) {
        LOG.info("Executing operation charges");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        System.out.println(insCompanyCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#banks(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void banks(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation banks");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#insSubCategories(nav.dynamics.microsoft.xmlports.tables.Root iTable, java.lang.String insCategoryCode)*
     */
    public void insSubCategories(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable, java.lang.String insCategoryCode) {
        LOG.info("Executing operation insSubCategories");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#endorsementReasons(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void endorsementReasons(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation endorsementReasons");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#coverCategories(nav.dynamics.microsoft.xmlports.tables.Root iTable, java.lang.String insCategoryCode)*
     */
    public void coverCategories(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable, java.lang.String insCategoryCode) {
        LOG.info("Executing operation coverCategories");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#taxOffices(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void taxOffices(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation taxOffices");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#packages(nav.dynamics.microsoft.xmlports.tables.Root iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode, java.lang.String insObjectTypeCode)*
     */
    public void packages(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode, java.lang.String insObjectTypeCode) {
        LOG.info("Executing operation packages");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        System.out.println(insCompanyCode);
        System.out.println(insObjectTypeCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#covers(nav.dynamics.microsoft.xmlports.covers.Root iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode)*
     */
    public void covers(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode) {
        LOG.info("Executing operation covers");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        System.out.println(insCompanyCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#discounts(nav.dynamics.microsoft.xmlports.discount_charges.Root iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode)*
     */
    public void discounts(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable, java.lang.String insCategoryCode, java.lang.String insCompanyCode) {
        LOG.info("Executing operation discounts");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        System.out.println(insCompanyCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#insCompanies(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void insCompanies(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation insCompanies");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#customFieldsTemplates(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void customFieldsTemplates(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation customFieldsTemplates");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#coversByPackage(nav.dynamics.microsoft.xmlports.covers.Root iTable, java.lang.String packageCode, java.lang.String insObjectTypeCode, java.lang.String insObjectTypeGroupCode, java.lang.String brokerNo, java.lang.String referenceDate)*
     */
    public void coversByPackage(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> iTable, java.lang.String packageCode, java.lang.String insObjectTypeCode, java.lang.String insObjectTypeGroupCode, java.lang.String brokerNo, java.lang.String referenceDate) {
        LOG.info("Executing operation coversByPackage");
        System.out.println(iTable.value);
        System.out.println(packageCode);
        System.out.println(insObjectTypeCode);
        System.out.println(insObjectTypeGroupCode);
        System.out.println(brokerNo);
        System.out.println(referenceDate);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#makes(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void makes(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation makes");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#vesselClassSociety(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void vesselClassSociety(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation vesselClassSociety");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#durationTypes(java.lang.String insCategory, nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void durationTypes(java.lang.String insCategory, javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation durationTypes");
        System.out.println(insCategory);
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#insCategories(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void insCategories(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation insCategories");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#countriesRegions(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void countriesRegions(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation countriesRegions");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#insObjectTypes(nav.dynamics.microsoft.xmlports.tables.Root iTable, java.lang.String insCategoryCode)*
     */
    public void insObjectTypes(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable, java.lang.String insCategoryCode) {
        LOG.info("Executing operation insObjectTypes");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#chargesByPackage(nav.dynamics.microsoft.xmlports.discount_charges.Root iTable, java.lang.String packageCode, java.lang.String insCategoryCode, java.lang.String insCompanyCode)*
     */
    public void chargesByPackage(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable, java.lang.String packageCode, java.lang.String insCategoryCode, java.lang.String insCompanyCode) {
        LOG.info("Executing operation chargesByPackage");
        System.out.println(iTable.value);
        System.out.println(packageCode);
        System.out.println(insCategoryCode);
        System.out.println(insCompanyCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#models(nav.dynamics.microsoft.xmlports.tables.Root iTable, java.lang.String makeCode)*
     */
    public void models(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable, java.lang.String makeCode) {
        LOG.info("Executing operation models");
        System.out.println(iTable.value);
        System.out.println(makeCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#vehicleTypes(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void vehicleTypes(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation vehicleTypes");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#professions(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void professions(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation professions");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#customFields(nav.dynamics.microsoft.xmlports.covers.Root iTable)*
     */
    public void customFields(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> iTable) {
        LOG.info("Executing operation customFields");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#customerDiscountGroups(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void customerDiscountGroups(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation customerDiscountGroups");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#colors(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void colors(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation colors");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#customFieldsValues(java.lang.String code, nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void customFieldsValues(java.lang.String code, javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation customFieldsValues");
        System.out.println(code);
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#customFieldsPerTemplate(java.lang.String templateCode, nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void customFieldsPerTemplate(java.lang.String templateCode, javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation customFieldsPerTemplate");
        System.out.println(templateCode);
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#brokers(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void brokers(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation brokers");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#vesselTypes(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void vesselTypes(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation vesselTypes");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#ports(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void ports(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation ports");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#attachedDocumentTypes(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void attachedDocumentTypes(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation attachedDocumentTypes");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#discountsByPackage(nav.dynamics.microsoft.xmlports.discount_charges.Root iTable, java.lang.String packageCode, java.lang.String insCategoryCode, java.lang.String insCompanyCode)*
     */
    public void discountsByPackage(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable, java.lang.String packageCode, java.lang.String insCategoryCode, java.lang.String insCompanyCode) {
        LOG.info("Executing operation discountsByPackage");
        System.out.println(iTable.value);
        System.out.println(packageCode);
        System.out.println(insCategoryCode);
        System.out.println(insCompanyCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#relationTypes(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void relationTypes(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation relationTypes");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#counties(nav.dynamics.microsoft.xmlports.tables.Root iTable)*
     */
    public void counties(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable) {
        LOG.info("Executing operation counties");
        System.out.println(iTable.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see schemas.dynamics.microsoft.codeunit.webdatamgt.WebDataMgtPort#insObjectTypeGroups(nav.dynamics.microsoft.xmlports.tables.Root iTable, java.lang.String insCategoryCode, java.lang.String insSubCategoryCode)*
     */
    public void insObjectTypeGroups(javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable, java.lang.String insCategoryCode, java.lang.String insSubCategoryCode) {
        LOG.info("Executing operation insObjectTypeGroups");
        System.out.println(iTable.value);
        System.out.println(insCategoryCode);
        System.out.println(insSubCategoryCode);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
