package generatedSources.DataMgt.schemas.dynamics.microsoft.codeunit.webdatamgt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-18T00:50:38.754+02:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", name = "WebDataMgt_Port")
@XmlSeeAlso({generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.ObjectFactory.class, generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.ins_makes.ObjectFactory.class, generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.ObjectFactory.class, ObjectFactory.class, generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.ObjectFactory.class})
public interface WebDataMgtPort {

    @WebMethod(operationName = "MakesByType", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:MakesByType")
    @RequestWrapper(localName = "MakesByType", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.MakesByType")
    @ResponseWrapper(localName = "MakesByType_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.MakesByTypeResult")
    public void makesByType(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.ins_makes.Root> iTable,
        @WebParam(name = "makeType", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        int makeType
    );

    @WebMethod(operationName = "Charges", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Charges")
    @RequestWrapper(localName = "Charges", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Charges")
    @ResponseWrapper(localName = "Charges_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.ChargesResult")
    public void charges(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode,
        @WebParam(name = "insCompanyCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCompanyCode
    );

    @WebMethod(operationName = "Banks", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Banks")
    @RequestWrapper(localName = "Banks", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Banks")
    @ResponseWrapper(localName = "Banks_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.BanksResult")
    public void banks(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "InsSubCategories", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:InsSubCategories")
    @RequestWrapper(localName = "InsSubCategories", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsSubCategories")
    @ResponseWrapper(localName = "InsSubCategories_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsSubCategoriesResult")
    public void insSubCategories(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode
    );

    @WebMethod(operationName = "EndorsementReasons", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:EndorsementReasons")
    @RequestWrapper(localName = "EndorsementReasons", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.EndorsementReasons")
    @ResponseWrapper(localName = "EndorsementReasons_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.EndorsementReasonsResult")
    public void endorsementReasons(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "CoverCategories", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CoverCategories")
    @RequestWrapper(localName = "CoverCategories", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CoverCategories")
    @ResponseWrapper(localName = "CoverCategories_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CoverCategoriesResult")
    public void coverCategories(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode
    );

    @WebMethod(operationName = "TaxOffices", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:TaxOffices")
    @RequestWrapper(localName = "TaxOffices", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.TaxOffices")
    @ResponseWrapper(localName = "TaxOffices_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.TaxOfficesResult")
    public void taxOffices(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "Packages", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Packages")
    @RequestWrapper(localName = "Packages", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Packages")
    @ResponseWrapper(localName = "Packages_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.PackagesResult")
    public void packages(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode,
        @WebParam(name = "insCompanyCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCompanyCode,
        @WebParam(name = "insObjectTypeCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insObjectTypeCode
    );

    @WebMethod(operationName = "Covers", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Covers")
    @RequestWrapper(localName = "Covers", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Covers")
    @ResponseWrapper(localName = "Covers_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CoversResult")
    public void covers(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode,
        @WebParam(name = "insCompanyCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCompanyCode
    );

    @WebMethod(operationName = "Discounts", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Discounts")
    @RequestWrapper(localName = "Discounts", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Discounts")
    @ResponseWrapper(localName = "Discounts_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.DiscountsResult")
    public void discounts(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode,
        @WebParam(name = "insCompanyCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCompanyCode
    );

    @WebMethod(operationName = "InsCompanies", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:InsCompanies")
    @RequestWrapper(localName = "InsCompanies", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsCompanies")
    @ResponseWrapper(localName = "InsCompanies_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsCompaniesResult")
    public void insCompanies(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "CustomFieldsTemplates", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CustomFieldsTemplates")
    @RequestWrapper(localName = "CustomFieldsTemplates", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFieldsTemplates")
    @ResponseWrapper(localName = "CustomFieldsTemplates_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFieldsTemplatesResult")
    public void customFieldsTemplates(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "CoversByPackage", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CoversByPackage")
    @RequestWrapper(localName = "CoversByPackage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CoversByPackage")
    @ResponseWrapper(localName = "CoversByPackage_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CoversByPackageResult")
    public void coversByPackage(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> iTable,
        @WebParam(name = "packageCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String packageCode,
        @WebParam(name = "insObjectTypeCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insObjectTypeCode,
        @WebParam(name = "insObjectTypeGroupCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insObjectTypeGroupCode,
        @WebParam(name = "brokerNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String brokerNo,
        @WebParam(name = "referenceDate", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String referenceDate
    );

    @WebMethod(operationName = "Makes", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Makes")
    @RequestWrapper(localName = "Makes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Makes")
    @ResponseWrapper(localName = "Makes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.MakesResult")
    public void makes(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "VesselClassSociety", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:VesselClassSociety")
    @RequestWrapper(localName = "VesselClassSociety", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.VesselClassSociety")
    @ResponseWrapper(localName = "VesselClassSociety_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.VesselClassSocietyResult")
    public void vesselClassSociety(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "DurationTypes", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:DurationTypes")
    @RequestWrapper(localName = "DurationTypes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.DurationTypes")
    @ResponseWrapper(localName = "DurationTypes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.DurationTypesResult")
    public void durationTypes(

        @WebParam(name = "insCategory", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategory,
        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "InsCategories", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:InsCategories")
    @RequestWrapper(localName = "InsCategories", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsCategories")
    @ResponseWrapper(localName = "InsCategories_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsCategoriesResult")
    public void insCategories(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "CountriesRegions", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CountriesRegions")
    @RequestWrapper(localName = "CountriesRegions", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CountriesRegions")
    @ResponseWrapper(localName = "CountriesRegions_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CountriesRegionsResult")
    public void countriesRegions(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "InsObjectTypes", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:InsObjectTypes")
    @RequestWrapper(localName = "InsObjectTypes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsObjectTypes")
    @ResponseWrapper(localName = "InsObjectTypes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsObjectTypesResult")
    public void insObjectTypes(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode
    );

    @WebMethod(operationName = "ChargesByPackage", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:ChargesByPackage")
    @RequestWrapper(localName = "ChargesByPackage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.ChargesByPackage")
    @ResponseWrapper(localName = "ChargesByPackage_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.ChargesByPackageResult")
    public void chargesByPackage(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable,
        @WebParam(name = "packageCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String packageCode,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode,
        @WebParam(name = "insCompanyCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCompanyCode
    );

    @WebMethod(operationName = "Models", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Models")
    @RequestWrapper(localName = "Models", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Models")
    @ResponseWrapper(localName = "Models_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.ModelsResult")
    public void models(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable,
        @WebParam(name = "makeCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String makeCode
    );

    @WebMethod(operationName = "VehicleTypes", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:VehicleTypes")
    @RequestWrapper(localName = "VehicleTypes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.VehicleTypes")
    @ResponseWrapper(localName = "VehicleTypes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.VehicleTypesResult")
    public void vehicleTypes(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "Professions", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Professions")
    @RequestWrapper(localName = "Professions", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Professions")
    @ResponseWrapper(localName = "Professions_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.ProfessionsResult")
    public void professions(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "CustomFields", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CustomFields")
    @RequestWrapper(localName = "CustomFields", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFields")
    @ResponseWrapper(localName = "CustomFields_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFieldsResult")
    public void customFields(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.covers.Root> iTable
    );

    @WebMethod(operationName = "CustomerDiscountGroups", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CustomerDiscountGroups")
    @RequestWrapper(localName = "CustomerDiscountGroups", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomerDiscountGroups")
    @ResponseWrapper(localName = "CustomerDiscountGroups_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomerDiscountGroupsResult")
    public void customerDiscountGroups(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "Colors", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Colors")
    @RequestWrapper(localName = "Colors", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Colors")
    @ResponseWrapper(localName = "Colors_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.ColorsResult")
    public void colors(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "CustomFieldsValues", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CustomFieldsValues")
    @RequestWrapper(localName = "CustomFieldsValues", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFieldsValues")
    @ResponseWrapper(localName = "CustomFieldsValues_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFieldsValuesResult")
    public void customFieldsValues(

        @WebParam(name = "code", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String code,
        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "CustomFieldsPerTemplate", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:CustomFieldsPerTemplate")
    @RequestWrapper(localName = "CustomFieldsPerTemplate", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFieldsPerTemplate")
    @ResponseWrapper(localName = "CustomFieldsPerTemplate_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CustomFieldsPerTemplateResult")
    public void customFieldsPerTemplate(

        @WebParam(name = "templateCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String templateCode,
        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "Brokers", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Brokers")
    @RequestWrapper(localName = "Brokers", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Brokers")
    @ResponseWrapper(localName = "Brokers_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.BrokersResult")
    public void brokers(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "VesselTypes", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:VesselTypes")
    @RequestWrapper(localName = "VesselTypes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.VesselTypes")
    @ResponseWrapper(localName = "VesselTypes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.VesselTypesResult")
    public void vesselTypes(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "Ports", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Ports")
    @RequestWrapper(localName = "Ports", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Ports")
    @ResponseWrapper(localName = "Ports_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.PortsResult")
    public void ports(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "AttachedDocumentTypes", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:AttachedDocumentTypes")
    @RequestWrapper(localName = "AttachedDocumentTypes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.AttachedDocumentTypes")
    @ResponseWrapper(localName = "AttachedDocumentTypes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.AttachedDocumentTypesResult")
    public void attachedDocumentTypes(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "DiscountsByPackage", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:DiscountsByPackage")
    @RequestWrapper(localName = "DiscountsByPackage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.DiscountsByPackage")
    @ResponseWrapper(localName = "DiscountsByPackage_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.DiscountsByPackageResult")
    public void discountsByPackage(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.discount_charges.Root> iTable,
        @WebParam(name = "packageCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String packageCode,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode,
        @WebParam(name = "insCompanyCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCompanyCode
    );

    @WebMethod(operationName = "RelationTypes", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:RelationTypes")
    @RequestWrapper(localName = "RelationTypes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.RelationTypes")
    @ResponseWrapper(localName = "RelationTypes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.RelationTypesResult")
    public void relationTypes(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "Counties", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:Counties")
    @RequestWrapper(localName = "Counties", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.Counties")
    @ResponseWrapper(localName = "Counties_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.CountiesResult")
    public void counties(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable
    );

    @WebMethod(operationName = "InsObjectTypeGroups", action = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt:InsObjectTypeGroups")
    @RequestWrapper(localName = "InsObjectTypeGroups", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsObjectTypeGroups")
    @ResponseWrapper(localName = "InsObjectTypeGroups_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt", className = "schemas.dynamics.microsoft.codeunit.webdatamgt.InsObjectTypeGroupsResult")
    public void insObjectTypeGroups(

        @WebParam(mode = WebParam.Mode.INOUT, name = "iTable", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        javax.xml.ws.Holder<generatedSources.DataMgt.nav.dynamics.microsoft.xmlports.tables.Root> iTable,
        @WebParam(name = "insCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insCategoryCode,
        @WebParam(name = "insSubCategoryCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebDataMgt")
        java.lang.String insSubCategoryCode
    );
}
