package generatedSources.Inquiry.schemas.dynamics.microsoft.codeunit.webinquiry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-18T00:49:54.677+02:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebInquiry", name = "WebInquiry_Port")
@XmlSeeAlso({ObjectFactory.class, generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.ObjectFactory.class})
public interface WebInquiryPort {

    @WebMethod(operationName = "GetInquiry", action = "urn:microsoft-dynamics-schemas/codeunit/WebInquiry:GetInquiry")
    @RequestWrapper(localName = "GetInquiry", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebInquiry", className = "schemas.dynamics.microsoft.codeunit.webinquiry.GetInquiry")
    @ResponseWrapper(localName = "GetInquiry_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebInquiry", className = "schemas.dynamics.microsoft.codeunit.webinquiry.GetInquiryResult")
    public void getInquiry(

        @WebParam(mode = WebParam.Mode.INOUT, name = "insInquiry", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/WebInquiry")
        javax.xml.ws.Holder<generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.WebInquiry> insInquiry
    );
}
