
package generatedSources.Inquiry.schemas.dynamics.microsoft.codeunit.webinquiry;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-18T00:49:54.688+02:00
 * Generated source version: 3.5.0
 *
 */

public class WebInquiryPort_WebInquiryPort_Server{

    protected WebInquiryPort_WebInquiryPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new WebInquiry_PortImpl();
        String address = "https://soap.insnemo.gr:7047/WS/ws/AIG_UAT/Codeunit/WebInquiry?WSDL";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new WebInquiryPort_WebInquiryPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
