
package  generatedSources.Inquiry.schemas.dynamics.microsoft.codeunit.webinquiry;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-18T00:49:54.627+02:00
 * Generated source version: 3.5.0
 *
 */
public final class WebInquiryPort_WebInquiryPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:microsoft-dynamics-schemas/codeunit/WebInquiry", "WebInquiry");

    //private URL
    private WebInquiryPort_WebInquiryPort_Client() {
    }

    public WebInquiryPort_WebInquiryPort_Client(String st)
    {
        URL wsdlURL = WebInquiry.WSDL_LOCATION;


        WebInquiry ss = new WebInquiry(wsdlURL, SERVICE_NAME);
        WebInquiryPort port = ss.getWebInquiryPort();

        {
            System.out.println("Invoking getInquiry...");
            generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.WebInquiry _getInquiry_insInquiryVal = null;
            javax.xml.ws.Holder<generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.WebInquiry> _getInquiry_insInquiry = new javax.xml.ws.Holder<generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.WebInquiry>(_getInquiry_insInquiryVal);
            port.getInquiry(_getInquiry_insInquiry);

            System.out.println("getInquiry._getInquiry_insInquiry=" + _getInquiry_insInquiry.value);

        }

    }


    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebInquiry.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WebInquiry ss = new WebInquiry(wsdlURL, SERVICE_NAME);
        //ss.
        WebInquiryPort port = ss.getWebInquiryPort();
       // System.out.println("kslsm"+ss.getWSDLDocumentLocation());
        {
        System.out.println("Invoking getInquiry...");
        generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.WebInquiry _getInquiry_insInquiryVal = null;
        javax.xml.ws.Holder<generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.WebInquiry> _getInquiry_insInquiry = new javax.xml.ws.Holder<generatedSources.Inquiry.nav.dynamics.microsoft.xmlports.webinquiry.WebInquiry>(_getInquiry_insInquiryVal);
        port.getInquiry(_getInquiry_insInquiry);

        System.out.println("getInquiry._getInquiry_insInquiry=" + _getInquiry_insInquiry.value);

        }

        System.exit(0);
    }

}
